### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by CP1832** [EionRobb/pidgin-typing-sounds#1]
Hi Eion:

Would it be possible for you to provide the .dll(s) for this plugin?

Thanks in advance.

**Comment by EionRobb** [comment]
Unfortunately the dll's didn't get copied over during the shift from google code.  I've created a release at https://github.com/EionRobb/pidgin-typing-sounds/releases/tag/release with the dll :)

**Comment by CP1832** [comment]
Thanks a lot Eion
